/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\scene8\models\WawaOffice.glb 
*/

import React, { useRef, useLayoutEffect } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import gsap from 'gsap'


export const FLOOR_HEIGHT = 2.3
export const NB_FLOORS = 3

export function Office(props) {
  const { nodes, materials } = useGLTF('/scene8/models/WawaOffice.glb')
  const ref = useRef()
  const tl = useRef()
  const libraryRef = useRef()
  const atticRef = useRef()
  const scroll = useScroll()


  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration())
  })


  /* This `useLayoutEffect` hook is being used to create a timeline animation using the GreenSock Animation Platform (GSAP) library. Here's a breakdown of what it's doing: */

  useLayoutEffect(() => {
    tl.current = gsap.timeline()
    tl.current.to(
      ref.current.position,
      {
        duration: 2,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
      },
      0
    )

    // library
    tl.current.from(
      libraryRef.current.position,
      {
        duration: 0.5,
        x: -2,
      },
      0.5
    )
    tl.current.from(
      libraryRef.current.position,
      {
        duration: 0.5,
        y: -Math.PI/2,
      },
      0.5
    )


    // attic
    tl.current.from(
      atticRef.current.position,
      {
        duration: 1.5,
        y: 2,
      },
      0
    )
    tl.current.from(
      atticRef.current.position,
      {
        duration: 0.5,
        z: -2,
      },
      1.5
    )



  }, [])







  // Corrected version
  
  
  
  
  
  
  
  
  
  
  
  // useLayoutEffect(() => {
  //   tl.current = gsap.timeline();

  //   // VERTICAL ANIMATION
  //   tl.current.to(
  //     ref.current.position,
  //     {
  //       duration: 2,
  //       y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
  //     },
  //     0
  //   );

  //   // Office Rotation
  //   tl.current.to(
  //     ref.current.rotation,
  //     { duration: 1, x: 0, y: Math.PI / 6, z: 0 },
  //     0
  //   );
  //   tl.current.to(
  //     ref.current.rotation,
  //     { duration: 1, x: 0, y: -Math.PI / 6, z: 0 },
  //     1
  //   );

  //   // Office movement
  //   tl.current.to(
  //     ref.current.position,
  //     {
  //       duration: 1,
  //       x: -1,
  //       z: 2,
  //     },
  //     0
  //   );
  //   tl.current.to(
  //     ref.current.position,
  //     {
  //       duration: 1,
  //       x: 1,
  //       z: 2,
  //     },
  //     1
  //   );

  //   // LIBRARY FLOOR
  //   tl.current.from(
  //     libraryRef.current.position,
  //     {
  //       duration: 0.5,
  //       x: -2,
  //     },
  //     0.5
  //   );
  //   tl.current.from(
  //     libraryRef.current.rotation,
  //     {
  //       duration: 0.5,
  //       y: -Math.PI / 2,
  //     },
  //     0
  //   );

  //   // ATTIC
  //   tl.current.from(
  //     atticRef.current.position,
  //     {
  //       duration: 1.5,
  //       y: 2,
  //     },
  //     0
  //   );

  //   tl.current.from(
  //     atticRef.current.rotation,
  //     {
  //       duration: 0.5,
  //       y: Math.PI / 2,
  //     },
  //     1
  //   );

  //   tl.current.from(
  //     atticRef.current.position,
  //     {
  //       duration: 0.5,

  //       z: -2,
  //     },
  //     1.5
  //   );
  // }, []);



  return (<>


    <group {...props} dispose={null} ref={ref}>
      <mesh
        geometry={nodes['01_office'].geometry}
        material={materials['01']}
        rotation={[0, 0, 0]}
      />

      <group
        position={[0, 2.114, -2.23]}>

        <group ref={libraryRef}>
          <mesh
            geometry={nodes['02_library'].geometry}
            material={materials['02']}
            rotation={[0, 0, 0]}
          />
        </group>

      </group>
      <group
        position={[-1.97, 4.227, -2.199]}>
        <group ref={atticRef}>
          <mesh
            geometry={nodes['03_attic'].geometry}
            material={materials['03']}
            rotation={[0, 0, 0]}
          />
        </group>
      </group>
    </group>

  </>)
}

useGLTF.preload('/scene8/models/WawaOffice.glb')
